PrototipoLeitorTesseract/PrototipoLeitorTesseract/Models/Base64ImageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PrototipoLeitorTesseract.Models
{
    public class Base64ImageViewModel
    {
        [Required(ErrorMessage = $"O Campo {nameof(Base64String)} é obrigatório.")]
        public string Base64String { get; set; } = String.Empty;
    }
}

PrototipoLeitorTesseract/PrototipoLeitorTesseract/Models/ErrorViewModel.cs
namespace PrototipoLeitorTesseract.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrototipoLeitorTesseract/PrototipoLeitorTesseract/Models/NotaFiscalViewModel.cs
using PrototipoLeitorTesseract.Extensions;

namespace PrototipoLeitorTesseract.Models
{
    public class NotaFiscalViewModel
    {
        private readonly string _leituraCompleta = String.Empty;
        private readonly bool _html = false;

        public NotaFiscalViewModel(string text, bool html)
        {
            _leituraCompleta = text;
            _html = html;
        }

        public string LeituraCompleta => _html ? _leituraCompleta.TrocarQuebrasDeLinhaPorHtmlBr() : _leituraCompleta;
        public string CNPJ => _leituraCompleta.RegexPegarCNPJ();
        public string NumeroCupom => _leituraCompleta.RegexPegarNumeroCupom();
        public string ChaveCupom => _leituraCompleta.RegexChaveCupom();
        public string DataHoraCompra => _leituraCompleta.RegexDataHoraCompra();
        public string[] Produtos => _leituraCompleta.RegexPegarDadosProdutos();
    }
}

PrototipoLeitorTesseract/PrototipoLeitorTesseract/Controllers/HomeController.cs
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Structure;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PrototipoLeitorTesseract.Extensions;
using PrototipoLeitorTesseract.Models;
using PrototipoLeitorTesseract.Services;
using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Text.RegularExpressions;
using Tesseract;

namespace PrototipoLeitorTesseract.Controllers
{
    public class HomeController : Controller
    {
        private readonly ImageService _imgService;
        private readonly TesseractService _tesService;

        public HomeController()
        {
            _imgService = new ImageService();
            _tesService = new TesseractService();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> RealizarLeitura(IFormFile image)
        {
            try
            {
                var bytes = await _imgService.ImageFormatter(image);
                string text = _tesService.ReadImage(bytes);
                return Json(new NotaFiscalViewModel(text, true));
            }
            catch (Exception ex)
            {
                return BadRequest(new { success = false, result = ex.Message });
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrototipoLeitorTesseract/PrototipoLeitorTesseract/Controllers/NotaFiscalController.cs
using Microsoft.AspNetCore.Mvc;
using PrototipoLeitorTesseract.Extensions;
using PrototipoLeitorTesseract.Models;
using PrototipoLeitorTesseract.Services;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PrototipoLeitorTesseract.Controllers
{
    [Route("api/v1/nota-fiscal")]
    [ApiController]
    public class NotaFiscalController : ControllerBase
    {
        private readonly ImageService _imgService;
        private readonly TesseractService _tesService;

        public NotaFiscalController()
        {
            _imgService = new ImageService();
            _tesService = new TesseractService();
        }

        [DisableRequestSizeLimit]
        [HttpPost("ler-imagem/base64")]
        public IActionResult LerImagem([FromBody] Base64ImageViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var bytes = _imgService.ImageFormatter(model.Base64String);
                    string text = _tesService.ReadImage(bytes);
                    return Ok(new NotaFiscalViewModel(text, false));
                }
                else
                {
                    return BadRequest(model);
                }
            }
            catch (Exception ex)
            {
                return BadRequest(new { error = ex.Message });
            }
        }
    }
}

PrototipoLeitorTesseract/PrototipoLeitorTesseract/Views/Home/Index.cshtml
@{
    string title = "Leitor de Nota Fiscal";

    ViewData["Title"] = title;
}

<style>
    .loader {
        position: relative;
        width: 54px;
        height: 54px;
        border-radius: 10px;
    }

        .loader div {
            width: 8%;
            height: 24%;
            background: rgb(128, 128, 128);
            position: absolute;
            left: 50%;
            top: 30%;
            opacity: 0;
            border-radius: 50px;
            box-shadow: 0 0 3px rgba(0,0,0,0.2);
            animation: fade458 1s linear infinite;
        }

    @@keyframes fade458 {
        from {
            opacity: 1;
        }

        to {
            opacity: 0.25;
        }
    }

    .loader .bar1 {
        transform: rotate(0deg) translate(0, -130%);
        animation-delay: 0s;
    }

    .loader .bar2 {
        transform: rotate(30deg) translate(0, -130%);
        animation-delay: -1.1s;
    }

    .loader .bar3 {
        transform: rotate(60deg) translate(0, -130%);
        animation-delay: -1s;
    }

    .loader .bar4 {
        transform: rotate(90deg) translate(0, -130%);
        animation-delay: -0.9s;
    }

    .loader .bar5 {
        transform: rotate(120deg) translate(0, -130%);
        animation-delay: -0.8s;
    }

    .loader .bar6 {
        transform: rotate(150deg) translate(0, -130%);
        animation-delay: -0.7s;
    }

    .loader .bar7 {
        transform: rotate(180deg) translate(0, -130%);
        animation-delay: -0.6s;
    }

    .loader .bar8 {
        transform: rotate(210deg) translate(0, -130%);
        animation-delay: -0.5s;
    }

    .loader .bar9 {
        transform: rotate(240deg) translate(0, -130%);
        animation-delay: -0.4s;
    }

    .loader .bar10 {
        transform: rotate(270deg) translate(0, -130%);
        animation-delay: -0.3s;
    }

    .loader .bar11 {
        transform: rotate(300deg) translate(0, -130%);
        animation-delay: -0.2s;
    }

    .loader .bar12 {
        transform: rotate(330deg) translate(0, -130%);
        animation-delay: -0.1s;
    }

</style>

<div class="card my-3">
    <div class="row g-0">
        <div class="col-md-4">
            <img id="imagemPreview" class="img-fluid rounded-start" src="~/images/sem-imagem.jpg" alt="Pré-visualização da Imagem">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h4 class="card-title">@title</h4>
                <div class="accordion mb-2">
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <a class="accordion-button">
                                (<strong>POST</strong>)&nbsp<strong>Endpoint:</strong>&nbsp;@Url.ActionLink("LerImagem", "NotaFiscal", null, Context.Request.Scheme, Context.Request.Host.Value)
                            </a>
                        </h2>
                        <div class="accordion-collapse collapse show">
                            <div class="accordion-body">
                                <code>
                                    {<br />
                                    &emsp;&emsp;"base64String": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAYGBgYHBgcICAcK..."
                                    <br />}
                                </code>
                            </div>
                        </div>
                    </div>
                </div>
                <form id="formulario" method="post" enctype="multipart/form-data">
                    <div class="input-group">
                        <input type="file" name="image" accept="image/*" class="form-control" id="image" aria-describedby="enviarFormulario" aria-label="Upload" required>
                        <button class="btn btn-success px-5" id="enviarFormulario" type="submit">Ler</button>
                    </div>
                </form>
                <div class="col">
                    <h5 class="text-danger" id="_error">Ocorreu um erro, tente novamente</h5>
                    <div id="loader" class="loader mt-2">
                        <div class="bar1"></div>
                        <div class="bar2"></div>
                        <div class="bar3"></div>
                        <div class="bar4"></div>
                        <div class="bar5"></div>
                        <div class="bar6"></div>
                        <div class="bar7"></div>
                        <div class="bar8"></div>
                        <div class="bar9"></div>
                        <div class="bar10"></div>
                        <div class="bar11"></div>
                        <div class="bar12"></div>
                    </div>
                </div>

                <section id="results">
                    <h5>Resultado</h5>
                    <div>
                        <div>
                            <h6>CNPJ:</h6>
                            <p id="cnpj"></p>
                        </div>
                        <div>
                            <h6>Número do Cupom:</h6>
                            <p id="numeroCupom"></p>
                        </div>
                        <div>
                            <h6>Chave do Cupom:</h6>
                            <p id="chaveCupom"></p>
                        </div>
                        <div>
                            <h6>Data e Hora da Compra:</h6>
                            <p id="dataHoraCompra"></p>
                        </div>
                        <div>
                            <h6>Produtos:</h6>
                            <div id="produtos"></div>
                        </div>
                    </div>
                    <div class="accordion mt-3" id="accordionExample">
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Leitura Completa
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <div id="_result" class="accordion-body"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#_error").hide();
            $("#results").hide();
            $("#loader").hide();

            $("#image").change(function () {
                exibirPrevisaoImagem(this);
            });
            $("#formulario").submit(function (event) {
                $("#_error").hide();
                $("#loader").show();
                $("#_result").hide();
                $("#results").hide();
                if (!this.checkValidity()) {
                    event.preventDefault();
                } else {
                    event.preventDefault();
                    var formularioData = new FormData(this);

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("RealizarLeitura", "Home")',
                        data: formularioData,
                        contentType: false,
                        processData: false,
                        success: function (success) {
                            $("#loader").hide();
                            $("#_result").html(success.leituraCompleta);

                            $("#cnpj").text(success.cnpj);
                            $("#numeroCupom").text(success.numeroCupom);
                            $("#chaveCupom").text(success.chaveCupom);
                            $("#dataHoraCompra").text(success.dataHoraCompra);
                            $("#produtos").html("");
                            success.produtos.forEach((produto, index) => {
                                $("#produtos").append(`<p>${produto}</p>`)
                            });
                            $("#_result").show();
                            $("#results").show();
                        },
                        error: function (error) {
                            console.log(error.result);
                            $("#loader").hide();
                            $("#_error").show();
                        }
                    });
                }
            });
        });

        function exibirPrevisaoImagem(input) {
            if (input.files && input.files[0]) {
                var leitor = new FileReader();

                leitor.onload = function (e) {
                    $("#imagemPreview").attr("src", e.target.result);
                };

                leitor.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

PrototipoLeitorTesseract/PrototipoLeitorTesseract/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrototipoLeitorTesseract.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>